<?php
include '../public/layouts/header.phtml'; ?>
<div class="container">
    <div class="row">
        <?php if (isset($_SESSION['id'])) {
            if ($_SESSION['id'] === $eachDiscussion[0]['user_id'] && $eachDiscussion[0]['open'] == 1) { ?>
                <div class="icons">
                    <a href="" data-toggle="modal" data-target="#editModal" id="edit" data-id="<?= $_GET['id'] ?>">
                        <i class="fa fa-pencil" aria-hidden="true"></i></a>
                    <a data-toggle="modal" data-target="#archiveModal" id="archive" data-id="<?= $_GET['id'] ?>"><i
                                class="fa fa-times" aria-hidden="true"></i></a>
                </div>
            <?php }
        } ?>
        <div class="col-lg-8">
            <!-- Title -->
            <h1 class="mt-4" id="title"><?= $eachDiscussion[0]["title"]; ?></h1>
            <!-- Author -->
            <p class="lead">
                by <a href="#"></a><?= $eachDiscussion[0]["first_name"] . '  ' . $eachDiscussion[0]["last_name"]; ?>
            </p>
            <hr>
            <!-- Date/Time -->
            <p>Posted on <?= $eachDiscussion[0]["created_at"]; ?></p>
            <blockquote class="blockquote">
                <span class="mb-0" id="desc"><?= $eachDiscussion[0]["description"]; ?></span>
                <footer class="blockquote-footer">Created by
                    <cite title="Source Title"><a
                                href="#"></a><?= $eachDiscussion[0]["first_name"] . '  ' . $eachDiscussion[0]["last_name"]; ?></cite>
                </footer>
            </blockquote>
            <br>
            <?php
            if ($eachDiscussion[0]['open'] !== 0) {
                if (isset($_SESSION['id'])) { ?>
                    <!-- Comments Form -->
                    <div class="card my-4">
                        <h5 class="card-header">Leave a Comment:</h5>
                        <div class="card-body">
                            <form>
                                <div class="form-group">
                                    <textarea class="form-control" rows="3" id="input"></textarea>
                                    <input type="hidden" id="id" value="<?= $_GET['id']; ?>">
                                </div>
                                <button type="button" class="btn btn-primary submit" id="add-comment">Comment</button>
                            </form>
                        </div>
                    </div>
                    <script>CKEDITOR.replace('input');</script>

                <?php } else{ ?>
                    <div class="card my-4">
                        <h5 class="card-header">Leave a Comment:</h5>
                        <div class="card-body">
                            <form>
                                <div class="form-group">
                                    <textarea class="form-control" rows="3"></textarea>
                                </div>

                                <a href="login">
                                    <button type="button" class="btn btn-primary btn-lg">Login for leaving comment
                                    </button>
                                </a>
                            </form>
                        </div>
                    </div>
                <?php }
            } ?>
            <!-- Single Comment -->
            <div id="app"></div>
            <div class="media mb-4" id="none" hidden>

                <div class="media-body">
                    <div class="panel panel-default">
                        <div class="panel-heading" id="hd"><h5 class="mt-0" id="commenter_name"></h5>
                            <a onclick="deleteId(this)" data-toggle="modal" data-target="#bestModal"
                               data-id="" data-desc=""
                               class="mark"><i class="fa fa-check" aria-hidden="true"></i>Mark as best</a>
                            <button type="button" id="del" class="btn btn-info btn-lg" data-toggle="modal"
                                    data-target="#myModal" data-id=""
                                    data-post="" onclick="idForBestComment(this)">Delete <i class="fa fa-trash-o"
                                                                               aria-hidden="true"></i>
                            </button>
                        </div>
                        <div class="panel-body" id="comment_text"></div>
                        <div class="panel-footer"><span id="date"></span></div>
                    </div>

                </div>
                <br>
            </div>
            <?php foreach ($comments as $comment) { ?>
                <!-- Single Comment -->
                <div class="media mb-4" id="none" hidden>

                    <div class="media-body">
                        <div class="panel panel-default">
                            <div class="panel-heading" id="hd"><h5 class="mt-0" id="commenter_name"></h5>
                                <a onclick="idForBestComment(this)" data-toggle="modal" data-target="#bestModal"
                                   data-id="<?= $comment['id']; ?>" data-desc="<?= $comment['discussion_id']; ?>"
                                   class="mark"><i class="fa fa-check" aria-hidden="true"></i>Mark as best</a>

                                <button type="button" id="del" class="btn btn-info btn-lg" data-toggle="modal"
                                        data-target="#myModal" data-id=""
                                        data-post="" onclick="deleteId(this)">Delete <i class="fa fa-trash-o"
                                                                                   aria-hidden="true"></i>
                                </button>
                            </div>
                            <div class="panel-body"><p id="comment_text"></p></div>
                            <div class="panel-footer"><span id="date"></span></div>
                        </div>


                    </div>
                </div>
                <div class="media mb-4">

                    <div class="media-body">
                        <div class="panel panel-default">
                            <div class="panel-heading" id="hd">
                                <?php if ($comment['best'] === 1) { ?>
                                    <p class="best"><i class="fa fa-check" aria-hidden="true"></i>Best Answer</p>
                                <?php } ?>
                                <h5 class="mt-0"
                                    id="commenter_name"><?= $comment["first_name"] . ' ' . $comment["last_name"]; ?></h5>

                                <?php if (isset($_SESSION['id'])) {
                                    if ($eachDiscussion[0]['user_id'] === $_SESSION['id']) {
                                        if ($bestDiscussion === 0) { ?>
                                            <a href="comments/mark?id=<?= $comment['id']; ?>&desc=<?= $_GET['id']; ?>"
                                               class="mark"><i class="fa fa-check" aria-hidden="true"></i>Mark as
                                                best</a>
                                        <?php } else {
                                            if ($comment['best'] !== 1) { ?>
                                                <a onclick="idForBestComment(this)" data-toggle="modal"
                                                   data-target="#bestModal" data-id="<?= $comment['id']; ?>"
                                                   data-desc="<?= $comment['discussion_id']; ?>" class="mark"><i
                                                            class="fa fa-check" aria-hidden="true"></i>Mark as best</a>
                                            <?php }
                                        }
                                    } ?>

                                    <?php if (isset($_SESSION['id'])) {
                                        if ($comment['user_id'] === $_SESSION['id']) { ?>
                                            <button type="button" id="del" class="btn btn-info btn-lg"
                                                    data-toggle="modal"
                                                    data-target="#myModal" data-id="<?= $comment['id']; ?>"
                                                    data-post="<?= $comment['discussion_id']; ?>" onclick="deleteId(this)">
                                                Delete <i
                                                        class="fa fa-trash-o" aria-hidden="true"></i></button>

                                        <?php }
                                    }
                                } ?></div>
                            <div class="panel-body"><p id="comment_text"><?= $comment["comment"]; ?></p></div>
                            <div class="panel-footer"><span id="date"><?= $comment["created_at"]; ?></span></div>
                        </div>

                    </div>
                </div>


            <?php } ?>
            <!-- Modal -->
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" >&times;</button>
                            <h4 class="modal-title">Delete Comment</h4>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure ?</p>
                            <button id="no" data-dismiss="modal" type="button" class="btn btn-primary">No</button>
                            <a href="comments/delete" id="yes_get" onclick="deleteComment(this)">
                                <button id="yes" class="btn btn-primary">Yes</button>
                            </a>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>

                </div>
            </div>
            <!-- Best Answer Modal -->
            <div class="modal fade" id="bestModal" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Do you want to change best answer?</h4>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure ?</p>
                            <button id="no" type="button" data-dismiss="modal" class="btn btn-primary">No</button>
                            <a href="comments/mark" id="yes_get" onclick="markBestAnswer(this)">
                                <button id="yes" class="btn btn-primary">Yes</button>
                            </a>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>

                </div>
            </div>

            <!-- Edit Modal -->
            <div class="modal fade" id="editModal" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Edit your Discussion</h4>
                        </div>
                        <div class="modal-body">
                            <form action="discussion/edit" method="post">
                                <div class="form-group">
                                    <label for="title">Title:</label>
                                    <input type="text" required class="form-control" id="modal-title"
                                           placeholder="Edit title" name="title">
                                </div>
                                <div class="form-group">
                                    <label for="desc">Description:</label>
                                    <textarea type="text" required class="form-control" id="modal-desc"
                                              placeholder="Edit desciption" name="modal-desc"></textarea>
                                </div>
                                <input type="hidden" name="id" value="<?= $_GET['id']; ?>">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>

                </div>
            </div>
            <!--Archive Modal -->
            <div class="modal fade" id="archiveModal" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Do you want to close this discussion?</h4>
                        </div>
                        <div class="modal-body">
                            <form action="discussion/archive" method="post">

                                <input type="hidden" name="id" value="<?= $_GET['id']; ?>">
                                <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                                <button type="submit" class="btn btn-primary">Yes</button>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<?php include '../public/layouts/footer.phtml'; ?>
<script>CKEDITOR.replace('modal-desc');</script>
<script src="../../public/js/script.js"></script>