<?php
include '../public/layouts/header.phtml';
if (isset($_SESSION["id"])) { ?>
    <div class="container">
    <div class="container layout left">
        <p class="log">Have an idea?</p>
        <a href="discussion/create">
            <button type="button" class="btn btn-primary btn-lg">Create new discussion</button>
        </a>
    </div>
<?php } else { ?>
    <div class="container">
    <div class="container layout">
        <p class="log">For creating new discussion</p>
        <a href="login">
            <button type="button" class="btn btn-primary btn-lg">Login</button>
        </a> or <a href="register">
            <button type="button" class="btn btn-primary btn-lg">Sign Up</button>
        </a>
    </div>
<?php } ?>
    <link rel="stylesheet" href="../../public/css/home.css">
    <div class="container">
        <div class="row center">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#active"> <i class="fa fa-calendar-check-o"
                                                                                 aria-hidden="true"></i>
                                Active Discuusions</a></li>
                        <li><a data-toggle="tab" href="#archive"> Archive <i class="fa fa-archive"
                                                                           aria-hidden="true"></i></a></li>
                        <?php if (isset($_SESSION['id'])) { ?>
                            <li><a data-toggle="tab" href="#my"> My discussions <i class="fa fa-folder-o"
                                                                                      aria-hidden="true"></i>
                                </a></li>
                        <?php } ?>
                    </ul>
                </div>
                <div class="panel-body">
                    <div class="tab-content">
                        <div id="active" class="tab-pane fade in active">
                            <ul class="list-group">
                                <?php foreach ($activeDiscussions as $active) { ?>
                                    <li class="list-group-item">
                                        <div class="checkbox">
                                            <i class="fa fa-list-ul" aria-hidden="true"></i>
                                            <label for="checkbox">
                                                <a href='discussion?id=<?= $active["id"]; ?>' class="trash">
                                                <?= $active["title"]; ?>
                                            </label>
                                        </div>
                                        <div class="pull-right action-buttons">
                                           <i class="fa fa-eye" aria-hidden="true"></i>View</a>
                                        </div>
                                    </li>

                                <?php } ?>
                            </ul>
                        </div>
                        <div id="archive" class="tab-pane fade">
                            <ul class="list-group">
                                <?php foreach ($archiveDiscussions as $archive) { ?>

                                    <li class="list-group-item">
                                        <div class="checkbox">
                                            <i class="fa fa-list-ul" aria-hidden="true"></i>
                                                <a href='discussion?id=<?= $archive["id"]; ?>' class="trash"><?= $archive["title"]; ?>
                                        </div>
                                        <div class="pull-right action-buttons">
                                           <i class="fa fa-eye" aria-hidden="true"></i>View </a>
                                        </div>

                                    </li>

                                <?php } ?>
                            </ul>
                        </div>
                        <div id="my" class="tab-pane fade">
                            <ul class="list-group">
                                <?php foreach ($myDiscussions as $myDiscussion) { ?>
                                    <li class="list-group-item">
                                        <div class="checkbox">
                                            <i class="fa fa-list-ul" aria-hidden="true"></i>
                                            <label for="checkbox">
                                                <a href='discussion?id=<?= $myDiscussion["id"]; ?>' class="trash"> <?= $myDiscussion["title"]; ?>
                                            </label>
                                        </div>
                                        <div class="pull-right action-buttons">
                                           <i class="fa fa-eye" aria-hidden="true"></i>View</a>
                                        </div>
                                    </li>

                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-6">
                            <h6>
                                Total Count <span class="label label-info"><?= count($activeDiscussions); ?></span></h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
<?php include '../public/layouts/footer.phtml'; ?>