<?php include '../public/layouts/header.phtml'; ?>
<div class="all">
        <div id="container_demo" >
            <div id="wrapper">
                <div id="login" class="animate form">
                    <?= $success; ?>
                    <form  action="login" method="post" autocomplete="on">
                        <h1>Log in</h1>
                        <p>
                            <label for="email" class="uname" > Your email  </label>
                            <input id="email" name="email" required="required" type="text" placeholder="mymail@mail.com"/>
                        </p>
                        <p>
                            <label for="password" class="youpasswd"> Your password </label>
                            <input id="password" name="password" required="required" type="password" placeholder="eg. X8df!90EO" />
                        </p>
                        <p class="keeplogin">
                            <input type="checkbox" name="loginkeeping" id="loginkeeping" value="loginkeeping" />
                            <label for="loginkeeping">Keep me logged in</label>
                        </p>
                        <p class="signin button">
                            <input type="submit" value="Log In"/>
                        </p>
                        <p class="change_link">
                            Not a member yet ?
                            <a href="register" class="to_register">Join us</a>
                        </p>
                    </form>
                </div>



            </div>
        </div>
    </section>
</div>
<?php include '../public/layouts/footer.phtml'; ?>